<h1 align="center">Zewail University of Science and Technology</h1>
<h2 align="center">CIE 417 (Fall 2018)</h2>
<h2 align="center">Lab 1: Python Tutorial</h3>
<h3 align="center">20/09/2018</h3>

### Dynamically Typed Language

In [50]:
x = 1 #x is bound to a value of type int
x *= 2.1 #x is now bound to another value of type float
print (x)

2.1


### Conditional

In [52]:
x = 2
y = 1

if x == y:
    print("x equals y")
elif x > y:
    print ("x is greater than y")
else:
    print ("x is smaller than y")

x is greater than y


### Strings

In [65]:
x = "This is a single \
line written in two lines"  # \ is used to continue the statement in another line
print(x)

This is a single line written in two lines


In [66]:
x = '''This is a
three
    lines
        statement'''
print(x)

This is a
three
    lines
        statement


In [67]:
x = 'Hello World' 
print(x[0:5]) #strings are indexable

Hello


In [72]:
x = "20"
y = "18"
print(x + y) #strings can be concatenated using + operator

2018


In [86]:
#non-string objects can be converted to strings using str() or format()
x = "20"
y = 18
print(x + str(y))
print(x + format(y, "0.2f"))
print(x + format(y, "d"))

2018
2018.00
2018


In [87]:
x = "Hello"
x[1] = 's' #strings are immutable

TypeError: 'str' object does not support item assignment

### Lists

In [124]:
x = ["Hello", "World", "."]

In [125]:
#lists are indexable
print (x[0])

Hello


In [126]:
#lists are mutable
print (x[2])
x[2] = "!"
print (x[2])

.
!


In [127]:
#appending items at the end
x.append("!")
print (x)

['Hello', 'World', '!', '!']


In [128]:
#inserting items in the middle
x.insert(1,",")
print (x)

['Hello', ',', 'World', '!', '!']


In [131]:
#slicing
x[0:2] = ['Hello,', ' ']
print(x)

['Hello,', ' ', 'World', '!', '!']


In [133]:
#lists Concatenation
x = ["Hello", ", "]
y = ["World", "!"]
print(x + y)

['Hello', ', ', 'World', '!']


In [136]:
#lists within lists
x = ["Hello", [", ", "World"], "!"]
print(x[1])
print(x[1][0])

[', ', 'World']
, 


### Tuples

In [151]:
x= ("Hello", ",")
y = "World", "!"  #This is also a tuple

In [152]:
#indexing
print(x[0])

#slicing
print (x[0:2])

#concatenating
print (x + y)

Hello
('Hello', ',')
('Hello', ',', 'World', '!')


In [153]:
#tuples are immutable
x[0] = "s"

TypeError: 'tuple' object does not support item assignment

In [156]:
#unpacking tuples
var1, var2 = x
print(var1)
print(var2)

Hello
,


### Sets

In [163]:
#sets are unordered and don't contain duplicates
x = set([1,2,3,1,2])
y = set("Hello")
print(x)
print(y)

{1, 2, 3}
{'e', 'H', 'l', 'o'}


In [166]:
x = set([1,2,3])
y = set([2,4,6])

#union
print (x | y)

#intersection
print (x & y)

#difference
print (x - y)

#symmetric difference
print (x ^ y)

{1, 2, 3, 4, 6}
{2}
{1, 3}
{1, 3, 4, 6}


In [173]:
#single items can be added using add(), multiple items can be added using update()
x.add(4)
y.update([6,8,10])
print(x)
print(y)

In [177]:
#items can be removed using remove()
x.remove(3)
print(x)

{1, 2, 4}


### Dictionaries

In [7]:
#dictionary initialization
student = {"name" : "Ahmed", "id":20150001, "courses":["CIE 417", "CIE 418", "CIE 419"]}

#accessing members
print(student["name"])

Ahmed


In [11]:
#check for a dictionary member, and add it if it is not found
if "GPA" in student:
    print(student)
else:
    student["GPA"] = 1.00
    print(student)

{'name': 'Ahmed', 'id': 20150001, 'courses': ['CIE 417', 'CIE 418', 'CIE 419'], 'GPA': 1.0}


In [10]:
#get() function returns the value if found, or return a default value if not
name = student.get("name", "Mohamed")
number = student.get("number", "01000000000")
print(name,number)

Ahmed 01000000000


In [12]:
#delete dictionary member
del student["GPA"]
print(student)

{'name': 'Ahmed', 'id': 20150001, 'courses': ['CIE 417', 'CIE 418', 'CIE 419']}


In [20]:
#get a list of dictionary keys using list(student)
print (list(student))

['name', 'id', 'courses']


### Iteration

In [23]:
#while loop
x = 5
while x:
    print(x)
    x -= 1

5
4
3
2
1


In [31]:
#for loop using range
for i in range(6):
    print(i,end=" ")
    
print("")
for i in range(5, 11):
    print(i,end=" ")
    
print("")
for i in range(0, 11, 2):
    print(i,end=" ")

0 1 2 3 4 5 
5 6 7 8 9 10 
0 2 4 6 8 10 

In [42]:
#iterating over iterables

#iterating over the characters of a string
x = "Hello"
for c in x:
    print (c, end=" ")
    
#iterating over a list
print("\n")
x = ["W", "o", "r", "l", "d"]
for c in x:
    print (c, end=" ")
    
#iterating over a dictionary
print("\n")
student = {"name" : "Ahmed", "id":20150001, "courses":["CIE 417", "CIE 418", "CIE 419"]}
for key in student:
    print (key, student[key])
    
#iterating over a list of tuples
print("\n")
student = [("Ahmed", 20150001, ["CIE 417", "CIE 418", "CIE 419"]), ("Mohamed", 20150002, ["CIE 417", "CIE 418", "CIE 419"])]
for name, uni_id, courses in student:
    print (name, uni_id, courses)

H e l l o 

W o r l d 

name Ahmed
id 20150001
courses ['CIE 417', 'CIE 418', 'CIE 419']


Ahmed 20150001 ['CIE 417', 'CIE 418', 'CIE 419']
Mohamed 20150002 ['CIE 417', 'CIE 418', 'CIE 419']


In [47]:
#list comprehension, for example create a list of even numbers as strings
y = [str(i) for i in range(20) if i%2==0]
print(y)

['0', '2', '4', '6', '8', '10', '12', '14', '16', '18']


### Functions

In [49]:
def power(x, y=2): #y has a default value
    result = x**y
    return result

Result = power(3,3)
print (Result)

Result = power(3) #use default value of y
print (Result)

Result = power(x=3,y=3) #to remove ambiguities
print (Result)

27
9
27


In [59]:
#we can choose what parameters to use if they have default values
def date(year, month=1, day=1):
    print(f"{day}/{month}/{year}")
    
date(2018)
date(2018, day=20)
date(2018, day=20, month=9) #arbitrary order

1/1/2018
20/1/2018
20/9/2018


In [60]:
#return multiple outputs
def reverse_inputs(x,y):
    return y,x #a tuple

x = 1
y = 2
print (f"x = {x}, y = {y}")

x,y = reverse_inputs(x,y) #unpack resulting tuple
print (f"x = {x}, y = {y}")

result = reverse_inputs(x,y) #return as a tuple
print (result)

x = 1, y = 2
x = 2, y = 1
(1, 2)


In [81]:
#use global keyword inside function to change the global variable and not the local variable
x = ["s"]
def foo_local():
    x = ["y"]
    print("foo_local")
    print(f"local x = {x}")

foo_local()
print(f"global x = {x}\n")

x = ["s"]
def foo_global():
    global x
    x = ["y"]
    print("foo_local")
    print(f"local x = {x}")

foo_global()
print(f"global x = {x}\n")

foo_local
local x = ['y']
global x = ['s']

foo_local
local x = ['y']
global x = ['y']



### Classes

In [90]:
class Stack(object):
    def __init__(self): #Initialize the stack
        self.stack = [ ]
    def push(self,object):
        self.stack.append(object)
    def pop(self):
        return self.stack.pop()
    def length(self):
        return len(self.stack)

In [112]:
x = Stack() #create a new object x
x.push("h")
x.push(["e","l"])
x.push(("l","o"))

In [113]:
x.length()

3

In [114]:
while x.length() > 0:
    print(x.pop())

('l', 'o')
['e', 'l']
h


### Numpy

In [121]:
import numpy as np

In [138]:
#array initialization from list
x = [[1,2,3],[4,5,6]]
x_np = np.array(x, dtype=np.float64)
print(type(x_np))
print(x_np)
print(f"shape: {x_np.shape}")

<class 'numpy.ndarray'>
[[1. 2. 3.]
 [4. 5. 6.]]
shape: (2, 3)


In [147]:
#array initialization from ones or zeros
x = np.ones((2,3))
y = np.zeros((3,3,2))
print(x)
print(f"shape: {x.shape}\n")
print(y)
print(f"shape: {y.shape}\n")

[[1. 1. 1.]
 [1. 1. 1.]]
shape: (2, 3)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
shape: (3, 3, 2)



In [153]:
#initialization from identity
x = np.eye(4)
y = np.identity(4)
print(x)
print("")
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [135]:
#np.arange is similar to the noral range
print (np.arange(0,10,2))

array([0, 2, 4, 6, 8])

In [164]:
#casting
x = np.array(["1","2","3"])
print(x)
x = x.astype(np.int32)
print(x)

['1' '2' '3']
[1 2 3]


In [182]:
#Arithematic operations between equal-sized arrays
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])

print(x*y)
print()
print(x+y)
print()
print(x-y)
print()
print(x/y)
print()
print(x**y)

[[ 2  4  6]
 [12 15 18]]

[[3 4 5]
 [7 8 9]]

[[-1  0  1]
 [ 1  2  3]]

[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]

[[  1   4   9]
 [ 64 125 216]]


In [183]:
#Arithematic operations between arrays and scalars
x = np.array([[1,2,3],[4,5,6]])

print(x*2)
print()
print(x+2)
print()
print(2-x)
print()
print(2/x)
print()
print(x**2)

[[ 2  4  6]
 [ 8 10 12]]

[[3 4 5]
 [6 7 8]]

[[ 1  0 -1]
 [-2 -3 -4]]

[[2.         1.         0.66666667]
 [0.5        0.4        0.33333333]]

[[ 1  4  9]
 [16 25 36]]


In [221]:
#array slices are just views and not copies
x = np.ones((2,3,4))
print(x, end="\n\n\n")

x_slice = x[0,:2,1:] # 1: means from 1 till the end, :2 means from the beginning till 2
x_slice[:] = 10   #changing view(x_slice) changes original x
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


[[[ 1. 10. 10. 10.]
  [ 1. 10. 10. 10.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


In [219]:
#array.copy() creates a copy
x = np.ones((2,3,4))
print(x, end="\n\n\n")

x_slice = x[0,:2,1:].copy()
x_slice[:] = 10   #changing copy doesn't change original x
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [225]:
#transposing
x = np.arange(16).reshape((4,4))
print(x, end='\n\n')
print(x.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [231]:
#inverse
from numpy.linalg import inv
x = np.random.randn(4,4)
print(x, end='\n\n')
print(inv(x))

[[-0.42462901  1.56703972  1.41828385 -1.03116491]
 [ 0.5872827  -2.58689068  0.0616155   0.18681166]
 [-0.23664954  0.19633375  0.63850885  1.00975961]
 [ 2.14544751  1.50251017 -0.23995476 -1.70094855]]

[[-0.17164724  0.19055176  0.52754495  0.43815992]
 [-0.05145505 -0.3430007   0.1865854   0.104288  ]
 [ 0.47170345  0.35416108  0.50373792  0.0519778 ]
 [-0.32849869 -0.11259945  0.75916004  0.04954328]]


In [239]:
#determinant
x = np.random.randint(5, size=(3,3))
print(x)
np.linalg.det(x)

[[3 1 2]
 [2 1 0]
 [4 3 2]]


6.0

In [241]:
#trace
x = np.random.randint(5, size=(3,3))
print(x)
np.trace(x)

[[0 3 4]
 [3 4 4]
 [1 0 2]]


6

In [260]:
#eigenvalues and eigenvectors
x = np.random.randn(3,3)
print(x, end='\n\n')
eigenvalues, eigenvectors = np.linalg.eig(x)
print(f"eigenvalues = {eigenvalues}\ncorresponding eigenvectors = \n{eigenvectors}")

[[ 0.6483711   0.2199622  -1.16126007]
 [ 0.02669981  0.03393603 -1.22005731]
 [-1.15307105 -2.15821486  1.11992944]]

eigenvalues = [ 2.7758426   0.36542654 -1.33903258]
corresponding eigenvectors = 
[[-0.47522548 -0.89279504  0.34350019]
 [-0.36155588  0.4293791   0.62009506]
 [ 0.80214593 -0.13620061  0.70532952]]


In [267]:
#solve
a = np.array([[1,2,3],[2,3,5],[3,1,4]])
b = np.array([1,2,3])
x = np.linalg.solve(a,b)
print(f"{a} x {x} = {b}")

[[1 2 3]
 [2 3 5]
 [3 1 4]] x [ 0.65384615 -0.34615385  0.34615385] = [1 2 3]


In [278]:
#least square solution for y = wx + b
x = np.array([0, 1, 2, 3])
A = np.vstack([x, np.ones(len(x))]).T #include the bias term in A
y = np.array([-1, 0.2, 0.9, 2.1])

w, b = np.linalg.lstsq(A,y, rcond=None)[0]
print(round(w,2),round(b,2))

1.0 -0.95


### Resources
* https://docs.python.org/3/tutorial/introduction.html
* Python for Data Analysis by Wes McKinney (1st Edition)
* Python Essential Reference by David Beazley (4th Edition)
* https://pandas.pydata.org/pandas-docs/stable/10min.html (for a pandas quick tutorial)
* https://nlp.stanford.edu/IR-book/html/htmledition/linear-algebra-review-1.html